#!/bin/sh

# List variables
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="robbyrussell"
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
export COMPOSER_ALLOW_SUPERUSER=1